databases:
  - name: blog-db
    databaseName: blog_db
    user: blog_user

services:
  - type: web
    name: blog-app
    rootDir: projects_code/blog_app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: SITE_DOMAIN
        value: "my-portfolio-yphw.onrender.com"
      - key: GOOGLE_CLIENT_ID
        sync: false   # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false   # Set manually in Render dashboard
