

services:
  - type: web
    name: blog-app
    rootDir: projects_code/blog_app
    env: python
    buildCommand: "sh ./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

      - key: SECRET_KEY
        generateValue: true
      - key: SITE_DOMAIN
        value: "blog-app-8lgh.onrender.com"
      - key: GOOGLE_CLIENT_ID
        sync: false   # Set manually in Render dashboard
      - key: GOOGLE_CLIENT_SECRET
        sync: false   # Set manually in Render dashboard
      - key: PYTHON_VERSION
        value: "3.12.2"

