services:
  - type: web
    name: blog-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blog_project.wsgi:application --bind 0.0.0.0:10000"
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
