@echo off
REM Open Render Dashboard for Deployment
REM This opens Render in your default browser and displays deployment steps

echo.
echo ========================================
echo   DEPLOY TO RENDER - QUICK START
echo ========================================
echo.
echo Your blog app is ready to deploy!
echo.
echo Opening Render.com in your browser...
echo Please sign up with GitHub when you arrive.
echo.
timeout /t 2

start https://render.com/dashboard

echo.
echo ========================================
echo   RENDER DEPLOYMENT CHECKLIST
echo ========================================
echo.
echo 1. ✅ Sign in with GitHub
echo 2. ✅ Click "New +" 
echo 3. ✅ Select "Web Service"
echo 4. ✅ Select "My_portfolio" repository
echo 5. ✅ Fill in settings (see below)
echo 6. ✅ Add environment variables
echo 7. ✅ Click "Create Web Service"
echo 8. ✅ Wait 5-10 minutes
echo 9. ✅ Copy the deployed URL (*.onrender.com)
echo 10. ✅ Send me the URL
echo.
echo ========================================
echo   COPY THIS CONFIGURATION
echo ========================================
echo.
echo NAME: blog-app
echo ENVIRONMENT: Python 3
echo REGION: Oregon (or closest to you)
echo.
echo BUILD COMMAND:
echo cd projects_code/blog_app && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
echo.
echo START COMMAND:
echo cd projects_code/blog_app && gunicorn blog_project.wsgi:application
echo.
echo ENVIRONMENT VARIABLES:
echo - SECRET_KEY = (auto-generated by Render)
echo - DEBUG = false
echo - ALLOWED_HOSTS = *.onrender.com
echo - SECURE_SSL_REDIRECT = true
echo - SESSION_COOKIE_SECURE = true
echo - CSRF_COOKIE_SECURE = true
echo.
echo ========================================
echo.
pause
